<a href="https://colab.research.google.com/github/gingerchien/ML-Intro/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Basics

* NumPy gives us the best of both worlds: element-by-element operations are the “default mode” when an ndarray is involved, but the element-by-element operation is speedily executed by pre-compiled C code
* Vectorization describes the absence of any explicit looping, indexing, etc., in the code - these things are taking place, of course, just “behind the scenes” in optimized, pre-compiled C code.
* NumPy fully supports an object-oriented approach, starting, once again, with ndarray. For example, ndarray is a class, possessing numerous methods and attributes. Many of its methods are mirrored by functions in the outer-most NumPy namespace, allowing the programmer to code in whichever paradigm they prefer. This flexibility has allowed the NumPy array dialect and NumPy ndarray class to become the de-facto language of multi-dimensional data interchange used in Python.




In NumPy dimensions are called axes.

# Important Attributes of an ndarray object:

* ndarray.ndim - the number of axes (dimensions) of the array.
* ndarray.shape - the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the number of axes, ndim.
* ndarray.size - the total number of elements of the array. This is equal to the product of the elements of shape
* ndarray.dtype - an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.
* ndarray.itemsize - the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize.
* ndarray.data - the buffer containing the actual elements of the array. Normally, we won’t need to use this attribute because we will access the elements in an array using indexing facilities.

In [1]:
import numpy as np
a = np.arange(15).reshape(3, 5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [2]:
a.ndim

2

In [3]:
a.shape

(3, 5)

In [4]:
a.dtype

dtype('int64')

In [8]:
type(a)

numpy.ndarray

In [5]:
a.size

15

In [6]:
a.itemsize

8

In [7]:
a.data

# Array Creation
There are several ways to create arrays.

For example, you can create an array from a regular Python list or tuple using the array function. The type of the resulting array is deduced from the type of the elements in the sequences.

In [11]:
a = np.array([2,3,4])
print(a)
a.dtype

[2 3 4]


dtype('int64')

In [12]:
b = np.array([(1.5,2,3), (4,5,6)])
print(b)
b.dtype

[[1.5 2.  3. ]
 [4.  5.  6. ]]


dtype('float64')

In [13]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
print(c)
c.dtype

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


dtype('complex128')

### Placeholder for Array Creation
NumPy offers several functions to create arrays with initial placeholder content. These minimize the necessity of growing arrays, an expensive operation.

The function zeros creates an array full of zeros, the function ones creates an array full of ones, and the function empty creates an array whose initial content is random and depends on the state of the memory. By default, the dtype of the created array is float64, but it can be specified via the key word argument dtype.

In [16]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.ones((2,3,4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [18]:
np.empty((2,3))

array([[1.39069238e-309, 1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309, 1.39069238e-309]])

### Creating Sequence of Numbers

In [19]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [21]:
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

When arange is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite floating point precision. For this reason, it is usually better to use the function linspace that receives as an argument the number of elements that we want, instead of the step:

In [22]:
from numpy import pi
x = np.linspace(0, 2*pi, 100)
f = np.sin(x)

# Printing Arrays

In [23]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [24]:
b = np.arange(12).reshape(4,3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [25]:
c = np.arange(24).reshape(2,3,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


If an array is too large to be printed, NumPy automatically skips the central part of the array and only prints the corners:

In [26]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [27]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


To disable this behaviour and force NumPy to print the entire array, you can change the printing options using set_printoptions.

In [28]:
#np.set_printoptions(threshold=sys.maxsize)  # sys module should be imported

# Basic Operations

In [29]:
a = np.array([20,30,40,50])
b = np.arange(4)
print(a)
print(b)

[20 30 40 50]
[0 1 2 3]


In [30]:
c = a-b
print(c)

[20 29 38 47]


In [31]:
b**2

array([0, 1, 4, 9])

In [32]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [33]:
a < 35

array([ True,  True, False, False])

 The product operator * operates elementwise in NumPy arrays. The matrix product can be performed using the @ operator (in python >=3.5) or the dot function or method:

In [34]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])
print(A)
print(B)

[[1 1]
 [0 1]]
[[2 0]
 [3 4]]


In [35]:
A*B

array([[2, 0],
       [0, 4]])

In [36]:
A@B

array([[5, 4],
       [3, 4]])

In [37]:
A.dot(B)

array([[5, 4],
       [3, 4]])

Some operations, such as += and *=, act in place to modify an existing array rather than create a new one

In [41]:
rg = np.random.default_rng(1)  # Random number generator instance
a = np.ones((2,3), dtype=int)
a *= 3
print(a)

[[3 3 3]
 [3 3 3]]


In [42]:
b = rg.random((2,3))
print(b)

[[0.51182162 0.9504637  0.14415961]
 [0.94864945 0.31183145 0.42332645]]


In [43]:
b += a
print(b)

[[3.51182162 3.9504637  3.14415961]
 [3.94864945 3.31183145 3.42332645]]


When operating with arrays of different types, the type of the resulting array corresponds to the more general or precise one (a behavior known as upcasting).

In [44]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0,pi,3)
b.dtype.name

'float64'

In [45]:
c = a + b
print(c)
c.dtype.name

[1.         2.57079633 4.14159265]


'float64'

In [46]:
d = np.exp(c*1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [47]:
d.dtype.name

'complex128'

Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods of the ndarray class.

In [48]:
a = np.random.random((2,3))
a

array([[0.76307407, 0.31267741, 0.58091179],
       [0.99044673, 0.30171312, 0.2740469 ]])

In [49]:
a.sum()

3.2228700183279715

In [50]:
a.min()

0.27404689619678313

In [51]:
a.max()

0.9904467272459611

By default, these operations apply to the array as though it were a list of numbers, regardless of its shape. However, by specifying the axis parameter you can apply an operation along the specified axis of an array:

In [52]:
b = np.arange(12).reshape(3,4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [53]:
b.sum(axis=0)  # sum of each column

array([12, 15, 18, 21])

In [54]:
b.min(axis=1)  # min of each row

array([0, 4, 8])

In [55]:
b.cumsum(axis=1)  # cumulative sum along each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

# Universal Functions
NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions” (ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.

In [56]:
B = np.arange(3)
print(B)

[0 1 2]


In [57]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [58]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [59]:
C = np.array([2., -1., 4.])
print(C)

[ 2. -1.  4.]


In [60]:
np.add(B,C)

array([2., 0., 6.])

# Indexing, Slicing and Iterating
One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.

In [61]:
a = np.arange(10)**3
print(a)

[  0   1   8  27  64 125 216 343 512 729]


In [62]:
a[2]

8

In [63]:
a[2:5]

array([ 8, 27, 64])

In [68]:
a[:6:2] = 1000  # equivalent to a[0:6:2] = -1000; from start to position 6, exclusive, set every 2nd element to -1000
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729])

In [69]:
a[::-1]  # reversed a

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000])

In [70]:
for i in a:
  print(i**(1/3.))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


**Multidimensional arrays** can have one index per axis. These indices are given in a tuple separated by commas:

In [72]:
def f(x,y):
  return 10*x+y
b = np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [73]:
b[2,3]

23

In [74]:
b[0:5,1]  # each row in the second column of b

array([ 1, 11, 21, 31, 41])

In [75]:
b[:,1] #equivalent of prev example

array([ 1, 11, 21, 31, 41])

In [76]:
b[1:3, :] #each column in the second and third row of b

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

When fewer indices are provided than the number of axes, the missing indices are considered complete slices:

In [77]:
b[-1]  # the last row. Equivalent to b[-1,:]

array([40, 41, 42, 43])

The expression within brackets in b[i] is treated as an i followed by as many instances of : as needed to represent the remaining axes. NumPy also allows you to write this using dots as b[i, ...].

The dots (...) represent as many colons as needed to produce a complete indexing tuple. For example, if x is an array with 5 axes, then

* x[1, 2, ...] is equivalent to x[1, 2, :, :, :],

* x[..., 3] to x[:, :, :, :, 3] and

* x[4, ..., 5, :] to x[4, :, :, 5, :].

In [78]:
c = np.array([[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]]])
print(c)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [79]:
c.shape

(2, 2, 3)

In [80]:
c[1,...]#same as c[1,:,:] or c[1]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

**Iterating** over multidimensional arrays is done with respect to the first axis:

In [81]:
for row in b:
  print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


However, if one wants to perform an operation on each element in the array, one can use the flat attribute which is an iterator over all the elements of the array:

In [82]:
for element in b.flat:
  print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


# Shape Manipulation

## Changing Shape of an Array
An array has a shape given by the number of elements along each axis:

In [84]:
a = np.floor(10 * rg.random((3,4)))
print(a)
print(a.shape)

[[2. 2. 7. 2.]
 [4. 9. 9. 7.]
 [5. 2. 1. 9.]]
(3, 4)


The shape of an array can be changed with various commands. Note that the following three commands all return a modified array, but do not change the original array:

In [85]:
a.ravel() #returns the array, flattened

array([2., 2., 7., 2., 4., 9., 9., 7., 5., 2., 1., 9.])

In [86]:
a.reshape(6,2) #returns the array with a modified shape

array([[2., 2.],
       [7., 2.],
       [4., 9.],
       [9., 7.],
       [5., 2.],
       [1., 9.]])

In [87]:
a.T #returns the array, transposed

array([[2., 4., 5.],
       [2., 9., 2.],
       [7., 9., 1.],
       [2., 7., 9.]])

In [88]:
a.T.shape

(4, 3)

In [89]:
a.shape

(3, 4)

The order of the elements in the array resulting from ravel is normally “C-style”, that is, the rightmost index “changes the fastest”, so the element after a[0, 0] is a[0, 1]. If the array is reshaped to some other shape, again the array is treated as “C-style”. NumPy normally creates arrays stored in this order, so ravel will usually not need to copy its argument, but if the array was made by taking slices of another array or created with unusual options, it may need to be copied. The functions ravel and reshape can also be instructed, using an optional argument, to use FORTRAN-style arrays, in which the leftmost index changes the fastest.

The reshape function returns its argument with a modified shape, whereas the ndarray.resize method modifies the array itself:

In [90]:
a

array([[2., 2., 7., 2.],
       [4., 9., 9., 7.],
       [5., 2., 1., 9.]])

In [91]:
a.resize(2,6)

In [92]:
a

array([[2., 2., 7., 2., 4., 9.],
       [9., 7., 5., 2., 1., 9.]])

If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated:

In [93]:
a.reshape(3,-1)

array([[2., 2., 7., 2.],
       [4., 9., 9., 7.],
       [5., 2., 1., 9.]])

## Stacking Together Different Arrays
Several arrays can be stacked together along different axes:

In [95]:
a = np.floor(10*rg.random((2,2)))
b = np.floor(10*rg.random((2,2)))
print(a)
print(b)

[[4. 0.]
 [6. 8.]]
[[5. 2.]
 [8. 5.]]


In [96]:
np.vstack((a,b)) #equivalent to row_stack

array([[4., 0.],
       [6., 8.],
       [5., 2.],
       [8., 5.]])

In [98]:
np.hstack((a,b))

array([[4., 0., 5., 2.],
       [6., 8., 8., 5.]])

The function column_stack stacks 1D arrays as columns into a 2D array. It is equivalent to hstack only for 2D arrays:

In general, for arrays with more than two dimensions, hstack stacks along their second axes, vstack stacks along their first axes, and concatenate allows for an optional arguments giving the number of the axis along which the concatenation should happen

In [99]:
from numpy import newaxis
a = np.array([4.,2.])
b = np.array([3.,8.])
np.column_stack((a,b))

array([[4., 3.],
       [2., 8.]])

In [100]:
np.hstack((a,b))

array([4., 2., 3., 8.])

In [101]:
a[:,newaxis] #view a as a 2D column vector

array([[4.],
       [2.]])

In [102]:
np.column_stack((a[:,newaxis],b[:,newaxis]))

array([[4., 3.],
       [2., 8.]])

In [103]:
np.hstack((a[:,newaxis],b[:,newaxis])) #same result as above

array([[4., 3.],
       [2., 8.]])

In [104]:
np.column_stack is np.hstack

False

In [105]:
np.row_stack is np.vstack

True

In complex cases, r_ and c_ are useful for creating arrays by stacking numbers along one axis. They allow the use of range literals :.

In [106]:
np.r_[1:4,0,4]

array([1, 2, 3, 0, 4])

## Splitting one array into several smaller ones

Using hsplit, you can split an array along its horizontal axis, either by specifying the number of equally shaped arrays to return, or by specifying the columns after which the division should occur:

In [107]:
a = np.floor(10 * rg.random((2,12)))
print(a)

[[5. 7. 1. 8. 6. 7. 1. 8. 1. 0. 8. 8.]
 [8. 4. 2. 0. 6. 7. 8. 2. 2. 6. 8. 9.]]


In [108]:
np.hsplit(a,3)

[array([[5., 7., 1., 8.],
        [8., 4., 2., 0.]]),
 array([[6., 7., 1., 8.],
        [6., 7., 8., 2.]]),
 array([[1., 0., 8., 8.],
        [2., 6., 8., 9.]])]

In [110]:
np.hsplit(a,(3,4)) #split a after the third and 4th column

[array([[5., 7., 1.],
        [8., 4., 2.]]),
 array([[8.],
        [0.]]),
 array([[6., 7., 1., 8., 1., 0., 8., 8.],
        [6., 7., 8., 2., 2., 6., 8., 9.]])]